### ISSUE TITLE
Internal server issue when converting audio to text 

### ISSUE THREAD

**Issue by medharthisharma02** [Kabanosk/website_for_whisper#17] opened 2023-07-27 09:14 UTC
**Describe the bug**
A clear and concise description of what the bug is the audio file is working ok on the browser , when the srt file download , file have a internal server error written in it 

**OS (please complete the following information):**
 - [e.g. iOS]
 Windows 

**Additional context**
![2023-07-27 14 43 17](https://github.com/Kabanosk/whisper-website/assets/132646196/445cd74d-0651-4ed4-9fd2-fbf4875da866)

**Comment by Kabanosk** [comment] 2023-07-27 10:12
1. Try to give it different name
2. (optional) you can remove lines 136 and 137 from the `src/main.py` file, but I am not 100% sure if that will work 

Edit: Can you please write if any of that solutions works?

**Comment by medharthisharma02** [comment] 2023-07-28 05:49
give a different name to what ? please elaborate

**Comment by medharthisharma02** [comment] 2023-07-28 05:56
okay , so after removing lines 136 and 137 from the src/main.py file , it's working perfectly.

**Comment by ilovefreesw** [comment] 2023-07-28 06:23
> Edit: Can you please write if any of that solutions works?

It looks from the above screenshots and a quick look at code that you forgot to close that file at line 136 ... that's why the error says the file is being used by other process. Just try closing it and it will work.

**Comment by Kabanosk** [comment] 2023-09-01 23:07
Hi! Sorry you had to wait - I had to pass my exams. Can you check if the code is working now? @avish-alumel @ilovefreesw

**Comment by Maduflavins** [comment] 2024-10-20 20:56
@Kabanosk looks like you fixed this because I could not reproduce this error locally

**Comment by Kabanosk** [comment] 2024-10-20 20:59
Thank you for the information @Maduflavins !

**Closed as completed** 2024-10-20 21:00 UTC
